#!/bin/bash

# Identifier les PID des processus gunicorn sur le port 8002
pids=$(lsof -ti tcp:8002)

# Tuer ces processus
for pid in $pids; do
    echo "Killing process $pid"
    kill -9 $pid
done

# Relancer le script
sh launch-alter_brain

